[profile.default]
src = './src'
out = './out'
libs = ['node_modules', 'lib']
test = './test/foundry'
cache_path  = 'cache_forge'
remappings = [
	'@ensdomains/=node_modules/@ensdomains/',
	'@oz-upgradeable/=lib/OZ-Upgradeable-Foundry/lib/openzeppelin-contracts-upgradeable/contracts/',
	'@oz/=lib/OZ-Upgradeable-Foundry/lib/openzeppelin-contracts/contracts/',
	'@prb/test/=lib/OZ-Upgradeable-Foundry/lib/prb-test/src/',
	'@std/=lib/OZ-Upgradeable-Foundry/lib/forge-std/src/',
	'OZ-Upgradeable-Foundry/=lib/OZ-Upgradeable-Foundry/',
	'ds-test/=lib/forge-std/lib/ds-test/src/',
	'@uniswap/v2-periphery/=lib/v2-periphery/',
    '@uniswap/v3-core/=lib/v3-core/',
    '@uniswap/v3-periphery/=lib/v3-periphery/',
	'@openzeppelin/=lib/openzeppelin-contracts/',
	'@openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/',
    '@forge-std/=lib/forge-std/'
]
optimizer = true
optimizer_runs = 500

# Fixed Version
solc_version = '0.8.20'
ffi = true
via-ir = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[fmt]
# Maximum line length where formatter will try to wrap the line
line_length = 100
# Number of spaces per indentation level
tab_width = 4
# Print spaces between brackets
bracket_spacing = false
# Style of uint/int256 types
int_types = "long"
# If function parameters are multiline then always put the function attributes on separate lines
func_attrs_with_params_multiline = true
# Style of quotation marks
quote_style = "double"
# Style of underscores in number literals
number_underscore = "preserve"
