[profile.default]
src = 'contracts'
out = 'out'
test = 'test/foundry'
libs = ['node_modules', 'lib']
solc_version = '0.8.17'
cache_path  = 'forge-cache'
remappings = [
    '@openzeppelin/=node_modules/@openzeppelin/',
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
]
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/tree/master/config